{{- if not .Values.mariadb.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" (include "scdf.fullname" .) "externaldb" }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
type: Opaque
data:
  mariadb-password: {{ .Values.externalDatabase.password | b64enc | quote }}
{{- end }}
